--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/kry_/.config/hypr/themes/Serenity/wallpaper.jpg"

-- Special
background="#121812"
foreground="#d2dade"
cursor="#d2dade"

-- Colors
color0="#121812"
color1="#4F6E9A"
color2="#778EB0"
color3="#759CDA"
color4="#93A2B3"
color5="#97B2D6"
color6="#8DB0E1"
color7="#d2dade"
color8="#93989b"
color9="#4F6E9A"
color10="#778EB0"
color11="#759CDA"
color12="#93A2B3"
color13="#97B2D6"
color14="#8DB0E1"
color15="#d2dade"
