--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/kry_/Imágenes/Wallpapers/292979.jpg"

-- Special
background="#0c0c0e"
foreground="#d0d6da"
cursor="#d0d6da"

-- Colors
color0="#0c0c0e"
color1="#384755"
color2="#4E5E6C"
color3="#81807E"
color4="#677886"
color5="#768995"
color6="#92A2AA"
color7="#d0d6da"
color8="#919598"
color9="#384755"
color10="#4E5E6C"
color11="#81807E"
color12="#677886"
color13="#768995"
color14="#92A2AA"
color15="#d0d6da"
