--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/kry_/.config/hypr/themes/Neon/wallpaper.jpg"

-- Special
background="#0a0406"
foreground="#e4d2d7"
cursor="#e4d2d7"

-- Colors
color0="#0a0406"
color1="#56425C"
color2="#9A1D1A"
color3="#C44750"
color4="#787089"
color5="#C96E95"
color6="#6CB1D2"
color7="#e4d2d7"
color8="#9f9396"
color9="#56425C"
color10="#9A1D1A"
color11="#C44750"
color12="#787089"
color13="#C96E95"
color14="#6CB1D2"
color15="#e4d2d7"
