# Shell variables
# Generated by 'wal'
wallpaper="/home/kry_/.config/hypr/themes/Stillness/wallpaper.png"

# Special
background='#0b101b'
foreground='#aab8d2'
cursor='#aab8d2'

# Colors
color0='#0b101b'
color1='#2C4FA1'
color2='#2C6DBD'
color3='#5675B1'
color4='#2C76C1'
color5='#417DC0'
color6='#A17397'
color7='#aab8d2'
color8='#768093'
color9='#2C4FA1'
color10='#2C6DBD'
color11='#5675B1'
color12='#2C76C1'
color13='#417DC0'
color14='#A17397'
color15='#aab8d2'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
