# Shell variables
# Generated by 'wal'
wallpaper="/home/kry_/.config/hypr/themes/Solitude/wallpaper.jpg"

# Special
background='#0a0f0f'
foreground='#bfa794'
cursor='#bfa794'

# Colors
color0='#0a0f0f'
color1='#433F3F'
color2='#59442F'
color3='#6C492D'
color4='#303B44'
color5='#3A434C'
color6='#5D4F4E'
color7='#bfa794'
color8='#857467'
color9='#433F3F'
color10='#59442F'
color11='#6C492D'
color12='#303B44'
color13='#3A434C'
color14='#5D4F4E'
color15='#bfa794'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
