--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/kry_/.config/hypr/themes/Solitude/wallpaper.jpg"

-- Special
background="#0a0f0f"
foreground="#bfa794"
cursor="#bfa794"

-- Colors
color0="#0a0f0f"
color1="#433F3F"
color2="#59442F"
color3="#6C492D"
color4="#303B44"
color5="#3A434C"
color6="#5D4F4E"
color7="#bfa794"
color8="#857467"
color9="#433F3F"
color10="#59442F"
color11="#6C492D"
color12="#303B44"
color13="#3A434C"
color14="#5D4F4E"
color15="#bfa794"
