# Shell variables
# Generated by 'wal'
wallpaper="/home/kry_/Imágenes/backgrounds/1378545.jpg"

# Special
background='#100a21'
foreground='#d9c1db'
cursor='#d9c1db'

# Colors
color0='#100a21'
color1='#4E53B7'
color2='#6559B9'
color3='#7039C9'
color4='#6765C7'
color5='#9B66D3'
color6='#B960CA'
color7='#d9c1db'
color8='#978799'
color9='#4E53B7'
color10='#6559B9'
color11='#7039C9'
color12='#6765C7'
color13='#9B66D3'
color14='#B960CA'
color15='#d9c1db'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
