--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/kry_/Imágenes/backgrounds/1378545.jpg"

-- Special
background="#100a21"
foreground="#d9c1db"
cursor="#d9c1db"

-- Colors
color0="#100a21"
color1="#4E53B7"
color2="#6559B9"
color3="#7039C9"
color4="#6765C7"
color5="#9B66D3"
color6="#B960CA"
color7="#d9c1db"
color8="#978799"
color9="#4E53B7"
color10="#6559B9"
color11="#7039C9"
color12="#6765C7"
color13="#9B66D3"
color14="#B960CA"
color15="#d9c1db"
