--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/kry_/.config/hypr/themes/Peek/wallpaper.png"

-- Special
background="#030510"
foreground="#82cce1"
cursor="#82cce1"

-- Colors
color0="#030510"
color1="#65124C"
color2="#3D4E69"
color3="#B34452"
color4="#0655A2"
color5="#0959A7"
color6="#DF6C8B"
color7="#82cce1"
color8="#5b8e9d"
color9="#65124C"
color10="#3D4E69"
color11="#B34452"
color12="#0655A2"
color13="#0959A7"
color14="#DF6C8B"
color15="#82cce1"
