--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/kry_/.config/hypr/themes/Dawn/wallpaper.jpg"

-- Special
background="#1f0f10"
foreground="#c3aa97"
cursor="#c3aa97"

-- Colors
color0="#1f0f10"
color1="#6D452A"
color2="#9E201D"
color3="#E6211F"
color4="#F50E21"
color5="#A24820"
color6="#E35020"
color7="#c3aa97"
color8="#887669"
color9="#6D452A"
color10="#9E201D"
color11="#E6211F"
color12="#F50E21"
color13="#A24820"
color14="#E35020"
color15="#c3aa97"
