# Shell variables
# Generated by 'wal'
wallpaper="/home/kry_/.config/hypr/themes/Eclipse/wallpaper.jpg"

# Special
background='#000D19'
foreground='#cf9a9b'
cursor='#cf9a9b'

# Colors
color0='#000D19'
color1='#233A48'
color2='#4E3C48'
color3='#6F3D48'
color4='#60444B'
color5='#8A3E48'
color6='#91444A'
color7='#cf9a9b'
color8='#906b6c'
color9='#233A48'
color10='#4E3C48'
color11='#6F3D48'
color12='#60444B'
color13='#8A3E48'
color14='#91444A'
color15='#cf9a9b'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
