--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/kry_/.config/hypr/themes/Eclipse/wallpaper.jpg"

-- Special
background="#000D19"
foreground="#cf9a9b"
cursor="#cf9a9b"

-- Colors
color0="#000D19"
color1="#233A48"
color2="#4E3C48"
color3="#6F3D48"
color4="#60444B"
color5="#8A3E48"
color6="#91444A"
color7="#cf9a9b"
color8="#906b6c"
color9="#233A48"
color10="#4E3C48"
color11="#6F3D48"
color12="#60444B"
color13="#8A3E48"
color14="#91444A"
color15="#cf9a9b"
