# Shell variables
# Generated by 'wal'
wallpaper="/home/kry_/.config/hypr/themes/Retro/wallpaper.png"

# Special
background='#0d1011'
foreground='#c5c0c1'
cursor='#c5c0c1'

# Colors
color0='#0d1011'
color1='#606063'
color2='#994037'
color3='#A27671'
color4='#9C8B6F'
color5='#42759A'
color6='#4896C3'
color7='#c5c0c1'
color8='#898687'
color9='#606063'
color10='#994037'
color11='#A27671'
color12='#9C8B6F'
color13='#42759A'
color14='#4896C3'
color15='#c5c0c1'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
