--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/kry_/Imágenes/backgrounds/1369680.jpeg"

-- Special
background="#0d0416"
foreground="#c39ed9"
cursor="#c39ed9"

-- Colors
color0="#0d0416"
color1="#6F2B8D"
color2="#692A96"
color3="#704AA1"
color4="#9B339F"
color5="#B0349C"
color6="#9B4FA7"
color7="#c39ed9"
color8="#886e97"
color9="#6F2B8D"
color10="#692A96"
color11="#704AA1"
color12="#9B339F"
color13="#B0349C"
color14="#9B4FA7"
color15="#c39ed9"
