# Shell variables
# Generated by 'wal'
wallpaper="/home/kry_/.config/hypr/themes/Serenity/wallpaper.jpg"

# Special
background='#121812'
foreground='#d2dade'
cursor='#d2dade'

# Colors
color0='#121812'
color1='#4F6E9A'
color2='#778EB0'
color3='#759CDA'
color4='#93A2B3'
color5='#97B2D6'
color6='#8DB0E1'
color7='#d2dade'
color8='#93989b'
color9='#4F6E9A'
color10='#778EB0'
color11='#759CDA'
color12='#93A2B3'
color13='#97B2D6'
color14='#8DB0E1'
color15='#d2dade'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
