# Shell variables
# Generated by 'wal'
wallpaper="/home/kry_/Imágenes/backgrounds/1369680.jpeg"

# Special
background='#0d0416'
foreground='#c39ed9'
cursor='#c39ed9'

# Colors
color0='#0d0416'
color1='#6F2B8D'
color2='#692A96'
color3='#704AA1'
color4='#9B339F'
color5='#B0349C'
color6='#9B4FA7'
color7='#c39ed9'
color8='#886e97'
color9='#6F2B8D'
color10='#692A96'
color11='#704AA1'
color12='#9B339F'
color13='#B0349C'
color14='#9B4FA7'
color15='#c39ed9'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
