[client]
## style file for the OSD

## on which height to show the OSD

## The maximum volume that can be reached in %
#max_volume = 150

## show percentage on the right of the OSD
# show_percentage = true

## set format for the media player OSD
#playerctl_format = "{artist} - {title}"
## Available values:
## artist, albumArtist, title, album, trackNumber, discNumber, autoRating

[server]

max_volume = 200
style = "/home/kry_/.config/swayosd/style.css"
top_margin = 0.85
