--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/kry_/.config/hypr/themes/Stillness/wallpaper.png"

-- Special
background="#0b101b"
foreground="#aab8d2"
cursor="#aab8d2"

-- Colors
color0="#0b101b"
color1="#2C4FA1"
color2="#2C6DBD"
color3="#5675B1"
color4="#2C76C1"
color5="#417DC0"
color6="#A17397"
color7="#aab8d2"
color8="#768093"
color9="#2C4FA1"
color10="#2C6DBD"
color11="#5675B1"
color12="#2C76C1"
color13="#417DC0"
color14="#A17397"
color15="#aab8d2"
