# Shell variables
# Generated by 'wal'
wallpaper="/home/kry_/Imágenes/Wallpapers/292979.jpg"

# Special
background='#0c0c0e'
foreground='#d0d6da'
cursor='#d0d6da'

# Colors
color0='#0c0c0e'
color1='#384755'
color2='#4E5E6C'
color3='#81807E'
color4='#677886'
color5='#768995'
color6='#92A2AA'
color7='#d0d6da'
color8='#919598'
color9='#384755'
color10='#4E5E6C'
color11='#81807E'
color12='#677886'
color13='#768995'
color14='#92A2AA'
color15='#d0d6da'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
