# Shell variables
# Generated by 'wal'
wallpaper="/home/kry_/.config/hypr/themes/Dawn/wallpaper.jpg"

# Special
background='#1f0f10'
foreground='#c3aa97'
cursor='#c3aa97'

# Colors
color0='#1f0f10'
color1='#6D452A'
color2='#9E201D'
color3='#E6211F'
color4='#F50E21'
color5='#A24820'
color6='#E35020'
color7='#c3aa97'
color8='#887669'
color9='#6D452A'
color10='#9E201D'
color11='#E6211F'
color12='#F50E21'
color13='#A24820'
color14='#E35020'
color15='#c3aa97'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
